### ISSUE TITLE
Text showing backwards on 10.3'' display

### ISSUE THREAD

**Issue by alienatorZ** [GregDMeyer/IT8951#37] opened 2021-07-07 16:15 UTC
Any idea why text would be backwards on the 10.3 display?

**Comment by GregDMeyer** [comment] 2021-07-07 18:59
Hmm, seems a duplicate of #25. Unfortunately I have no idea why this happens, I can't reproduce on my device. I think it might be some weird hardware configuration problem, it seems to only happen for some people. If you figure out what's going on please let me know!

There is a workaround mentioned in that other issue, where you can just flip the image in the code before displaying it, and it will display correctly. Sorry to not be able to help more!

**Closed by GregDMeyer** 2021-07-07 18:59 UTC
